### ISSUE TITLE
Storm UI internal ip address  - viewing executor logs

### ISSUE THREAD

**Issue by timmolter** [KasperMadsen/storm-deploy-alternative#19]
I'm hoping you have an idea to help with this issue. See screenshots below. Basically, I want to be able to view the logs the the Storm components are producing. the problem is that the Storm UI is using the internal ip addresses and of course, I cannot then connect from the outside. Do you have a solution for this?

Edit: I already checked an you added port 8000 to the security group. I also tried using the public ip address but got `ERR_CONNECTION_REFUSED` in the browser.

![screen shot 2015-12-22 at 8 48 57 pm](https://cloud.githubusercontent.com/assets/738972/11964408/bdcbb548-a8ed-11e5-94af-476a8541c1c8.png)
![screen shot 2015-12-22 at 8 48 43 pm](https://cloud.githubusercontent.com/assets/738972/11964409/bdd44ad2-a8ed-11e5-8128-fa47faef4b96.png)

**Comment by KasperMadsen** [comment]
I haven't tried to solve this yet, but I suspect one of the following approaches will do the trick.

* Change the deploy tool to give external ips in the storm.yaml while configuring
or
* Change the deploy tool to set the hostname of each node to the external ip

**Comment by darkn3rd** [comment]
One potential solution is to make hidden IP addresses behind a fire wall available to the public end point is to use a reverse proxy.  

The problem is that Storm fetches the private IP address DNS name, rather than any other A record you specify in the `storm.yaml`.  I am not sure how to change the behavior in used in `storm ui`. 

Why was this closed, this is a valid use case that needs to be supported, that is ability to configure/toggle what DNS names are used for the links for your supervisors.
