### ISSUE TITLE
Pull binaries from non-S3 URL, but from original source

### ISSUE THREAD

**Issue by timmolter** [KasperMadsen/storm-deploy-alternative#21]
For example, you pull down the SDA jar here: `https://s3-eu-west-1.amazonaws.com/storm-deploy-alternative`, which is (I'm guessing) your own s3 instance, right? Better would be to publish the SDA jar to Maven Central and pull it from there. 

Also for Storm and zookeeper, they could be downloaded from here: <https://storm.apache.org/downloads.html> and <https://www.apache.org/dyn/closer.cgi/zookeeper/>

What do you think? Are you willing to version DSA and push jars to Maven Central?

I made a guide on how to do that recently:
<http://knowm.org/a-practical-guide-to-uploading-artifacts-to-maven-central/>

**Comment by KasperMadsen** [comment]
Hi,
Publishing SDA.jar to Maven is indeed a possibility, but what is the gain?

For Storm and Zookeeper, I have chosen not to download from the original sources, because such paths often change. I want the deploy tool to be as independent of 3rd party changes as possible, which is why I use my own s3 instance ;)

**Comment by KasperMadsen** [comment]
no communication
